name = "Garlic"
author = "ramidzkh, GKasparov"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24d563afd69aee85dded4c1e021c55ba468c4e17ea5e26771fe8fa8a676a3599"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
