name = "Garlic"
author = "ramidzkh, GKasparov"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "945dc089bb23b1b3efc710f6c3ad77734b0c33b828b4f593b36fc2ff4d967da6"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
