name = "Garlic"
author = "ramidzkh, GKasparov"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e22ab1e2d3baab51f3e802cf7fa35f446db8d184dc936692ff73ee8c49fbb2e4"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
