name = "Garlic"
author = "ramidzkh, GKasparov"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69bfa430ab46d66ba5b4a253f78bd2e92122975bfb066bc2a70fd447b94bd80f"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
