name = "Garlic"
author = "ramidzkh, GKasparov"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "138a0d417e5d895631924274451c19840c931985fb01e85ae7aae4fa617630fa"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
