name = "Garlic"
author = "ramidzkh, GKasparov"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec6bd660b5193945e6ccd53849b1b63f7df93a7d74907f987add307c516fdd80"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
