name = "Garlic"
author = "ramidzkh, GKasparov"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eadf13bd60ec618debef70c4c0b60403e2c485556bbb80ae770fbbd57df9a23d"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
