name = "Garlic"
author = "ramidzkh, GKasparov"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f01261e7f503df242bac2bcccc1935b82cc9a8bb8fef022839582c3857e9592"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
