name = "Garlic"
author = "ramidzkh, GKasparov"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f04ef1ab93a35a9d9e4a8e1a123fae219d2589219d265f4d39d95b05f812912f"

[versions]
forge = "14.23.5.2855"
minecraft = "1.12.2"
