name = "CB Multipart"
filename = "ForgeMultipart-1.12.2-2.6.2.83-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2755/790/ForgeMultipart-1.12.2-2.6.2.83-universal.jar"
hash-format = "murmur2"
hash = "3090990458"

[update]
[update.curseforge]
file-id = 2755790
project-id = 258426
release-channel = "beta"
