name = "Mouse Tweaks"
filename = "MouseTweaks-2.10-mc1.12.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2671/937/MouseTweaks-2.10-mc1.12.2.jar"
hash-format = "murmur2"
hash = "533666569"

[update]
[update.curseforge]
file-id = 2671937
project-id = 60089
release-channel = "beta"
