name = "Storage Drawers"
filename = "StorageDrawers-1.12.2-5.4.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2952/606/StorageDrawers-1.12.2-5.4.2.jar"
hash-format = "murmur2"
hash = "880280580"

[update]
[update.curseforge]
file-id = 2952606
project-id = 223852
release-channel = "beta"
