name = "Thermal Expansion"
filename = "ThermalExpansion-1.12.2-5.5.7.1-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/2926/431/ThermalExpansion-1.12.2-5.5.7.1-universal.jar"
hash-format = "murmur2"
hash = "2287283150"

[update]
[update.curseforge]
file-id = 2926431
project-id = 69163
release-channel = "beta"
